config:
  target: 'http://localhost:8080'
  phases:
    - duration: 60
      arrivalRate: 1000

scenarios:
  - flow:
      - post:
          url: "/statistic/ru"
      - post:
          url: "/statistic/it"
      - post:
          url: "/statistic/us"
      - post:
          url: "/statistic/ua"
      - post:
          url: "/statistic/gb"
      - post:
          url: "/statistic/de"
      - get:
          url: "/statistic"


